# Generated by Django 4.0.1 on 2022-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=6)),
                ('to_currency_code', models.CharField(max_length=6)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=100)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
