version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    environment:
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Pass2020!
    ports:
    - 5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
  redis:
      image: redis:6.2-alpine
      container_name: redis
      ports:
        - 6379
  django:
    build: .
    container_name: django
    depends_on:
      - postgres
      - redis
    environment:
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Pass2020!
    volumes:
      - .:/api_service
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


  celery:
    build: .
    command: celery -A apirate worker -l info
    environment:
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Pass2020!
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A apirate beat -l info
    environment:
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Pass2020!
    depends_on:
      - redis
  
