version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: my_awesome_project_local_django
    container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/api_service
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:10.5
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Pass2020!
    ports:
    - '5432:5432'
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  redis:
      image: redis:6.2-alpine
      ports:
        - 6379:6379
      command: --name my-first-redis -d redis